### ISSUE TITLE
Error on boot of codespace

### ISSUE THREAD

**Issue by davidmhleung** [revodavid/devcontainers-rstudio#4]
Forked repo and tried creating codespace off of main but ran into the following error.

```
2022-12-15 06:58:08.963Z: #8 10.14 Building dependency tree...
2022-12-15 06:58:09.122Z: 
2022-12-15 06:58:09.122Z: #8 10.26 Reading state information...
2022-12-15 06:58:09.122Z: #8 10.30 E: Unable to locate package liblttng-ust0
2022-12-15 06:58:09.498Z: #8 ERROR: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && /bin/bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true"     && usermod -a -G staff ${USERNAME}     && apt-get -y install         python3-pip         libgit2-dev         libcurl4-openssl-dev         libssl-dev         libxml2-dev         libxt-dev     && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts     && python3 -m pip --no-cache-dir install radian     && pip --disable-pip-version-check --no-cache-dir install pybryt     && pip --disable-pip-version-check --no-cache-dir install pylint     && pip --disable-pip-version-check --no-cache-dir install jupyter     && pip --disable-pip-version-check --no-cache-dir install datascience     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install numpy     && pip --disable-pip-version-check --no-cache-dir install pandas     && pip --disable-pip-version-check --no-cache-dir install scipy     && pip --disable-pip-version-check --no-cache-dir install folium>=0.9.1     && pip --disable-pip-version-check --no-cache-dir install matplotlib     && pip --disable-pip-version-check --no-cache-dir install ipywidgets>=7.0.0     && pip --disable-pip-version-check --no-cache-dir install bqplot     && pip --disable-pip-version-check --no-cache-dir install nbinteract>=0.0.12     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install okpy     && pip --disable-pip-version-check --no-cache-dir install scikit-learn     && install2.r --error --skipinstalled --ncpus -1         languageserver         httpgd         statip         patchwork         paletteer         here         doParallel         janitor         vip         ranger         palmerpenguins         skimr         nnet         kernlab         plotly         factoextra         cluster         tidymodels         markdown         ottr     && rm -rf /tmp/downloaded_packages]: exit code: 100
2022-12-15 06:58:09.498Z: ------
2022-12-15 06:58:09.498Z:  > [dev_container_auto_added_stage_label  3/10] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && /bin/bash /tmp/library-scripts/common-debian.sh "true" "rstudio" "1000" "1000" "false" "true" "true"     && usermod -a -G staff rstudio     && apt-get -y install         python3-pip         libgit2-dev         libcurl4-openssl-dev         libssl-dev         libxml2-dev         libxt-dev     && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts     && python3 -m pip --no-cache-dir install radian     && pip --disable-pip-version-check --no-cache-dir install pybryt     && pip --disable-pip-version-check --no-cache-dir install pylint     && pip --disable-pip-version-check --no-cache-dir install jupyter     && pip --disable-pip-version-check --no-cache-dir install datascience     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install numpy     && pip --disable-pip-version-check --no-cache-dir install pandas     && pip --disable-pip-version-check --no-cache-dir install scipy     && pip --disable-pip-version-check --no-cache-dir install folium>=0.9.1     && pip --disable-pip-version-check --no-cache-dir install matplotlib     && pip --disable-pip-version-check --no-cache-dir install ipywidgets>=7.0.0     && pip --disable-pip-version-check --no-cache-dir install bqplot     && pip --disable-pip-version-check --no-cache-dir install nbinteract>=0.0.12     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install okpy     && pip --disable-pip-version-check --no-cache-dir install scikit-learn     && install2.r --error --skipinstalled --ncpus -1         languageserver         httpgd         statip         patchwork         paletteer         here         doParallel         janitor         vip         ranger         palmerpenguins         skimr         nnet         kernlab         plotly         factoextra         cluster         tidymodels         markdown         ottr     && rm -rf /tmp/downloaded_packages:
2022-12-15 06:58:09.498Z: 
2022-12-15 06:58:09.499Z: #8 5.942 Running apt-get update...
2022-12-15 06:58:09.499Z: #8 6.198 Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
2022-12-15 06:58:09.499Z: #8 6.326 Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
2022-12-15 06:58:09.499Z: #8 6.457 Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
2022-12-15 06:58:09.499Z: #8 6.588 Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
2022-12-15 06:58:09.499Z: 
2022-12-15 06:58:09.499Z: 
2022-12-15 06:58:09.499Z: #8 10.26 Reading state information...
2022-12-15 06:58:09.499Z: #8 10.30 E: Unable to locate package liblttng-ust0
2022-12-15 06:58:09.499Z: ------
2022-12-15 06:58:09.503Z: ERROR: failed to solve: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && /bin/bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true"     && usermod -a -G staff ${USERNAME}     && apt-get -y install         python3-pip         libgit2-dev         libcurl4-openssl-dev         libssl-dev         libxml2-dev         libxt-dev     && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts     && python3 -m pip --no-cache-dir install radian     && pip --disable-pip-version-check --no-cache-dir install pybryt     && pip --disable-pip-version-check --no-cache-dir install pylint     && pip --disable-pip-version-check --no-cache-dir install jupyter     && pip --disable-pip-version-check --no-cache-dir install datascience     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install numpy     && pip --disable-pip-version-check --no-cache-dir install pandas     && pip --disable-pip-version-check --no-cache-dir install scipy     && pip --disable-pip-version-check --no-cache-dir install folium>=0.9.1     && pip --disable-pip-version-check --no-cache-dir install matplotlib     && pip --disable-pip-version-check --no-cache-dir install ipywidgets>=7.0.0     && pip --disable-pip-version-check --no-cache-dir install bqplot     && pip --disable-pip-version-check --no-cache-dir install nbinteract>=0.0.12     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install okpy     && pip --disable-pip-version-check --no-cache-dir install scikit-learn     && install2.r --error --skipinstalled --ncpus -1         languageserver         httpgd         statip         patchwork         paletteer         here         doParallel         janitor         vip         ranger         palmerpenguins         skimr         nnet         kernlab         plotly         factoextra         cluster         tidymodels         markdown         ottr     && rm -rf /tmp/downloaded_packages]: exit code: 100
2022-12-15 06:58:09.523Z: Stop (56870 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.26.0-1671087432608/Dockerfile-with-features -t vsc-devcontainers-rstudio-bbfd0d6c0abb26cf4b2640ac7d450c49 --target dev_containers_target_stage --build-arg VARIANT=4 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/devcontainers-rstudio/.devcontainer
2022-12-15 06:58:09.523Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.26.0-1671087432608/Dockerfile-with-features -t vsc-devcontainers-rstudio-bbfd0d6c0abb26cf4b2640ac7d450c49 --target dev_containers_target_stage --build-arg VARIANT=4 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/devcontainers-rstudio/.devcontainer
2022-12-15 06:58:09.523Z:     at Zne (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1866:1635)
2022-12-15 06:58:09.523Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-12-15 06:58:09.523Z:     at async EF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1865:1963)
2022-12-15 06:58:09.523Z:     at async x7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1865:901)
2022-12-15 06:58:09.523Z:     at async oie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1871:2093)
2022-12-15 06:58:09.523Z:     at async qf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1871:3239)
2022-12-15 06:58:09.523Z:     at async Mse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1995:16211)
2022-12-15 06:58:09.523Z:     at async Lse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1995:15965)
2022-12-15 06:58:09.551Z: Stop (57928 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/devcontainers-rstudio --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/devcontainers-rstudio/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-12-15 06:58:09.551Z: Exit code 1

====================================== ERROR ====================================
2022-12-15 06:58:09.564Z: Failed to create container.
=================================================================================
2022-12-15 06:58:09.575Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/devcontainers-rstudio --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/devcontainers-rstudio/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-12-15 06:58:09.576Z: Error Code: 1302
```

**Comment by davidmhleung** [comment]
Looks related to liblttng-ust1 vs liblttng-ust0:

https://github.com/actions/runner/issues/1584
